### ISSUE TITLE
"Badly" formatted queries generate unhandled exception

### ISSUE THREAD

**Issue by ravishivt** [florianholzapfel/express-restify-mongoose#171]
If I do a GET query like ```/Customers?query={"name":"Bob"}```, it works fine.  But if I simply take out the quotes on the key like ```/Customers?query={name:"Bob"}```, the server crashes with the below exception.  I'm running 2.0.0.

```
TypeError: Cannot read property 'toString' of undefined
    at ServerResponse.writeHead (_http_server.js:190:44)
    at ServerResponse.writeHead (/Users/rmehra/esupport/code/asp_v4/node_modules/on-headers/index.js:53:19)
    at ServerResponse.writeHead (/Users/rmehra/esupport/code/asp_v4/node_modules/on-headers/index.js:53:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:544:10)
    at writeend (/Users/rmehra/esupport/code/asp_v4/node_modules/express-session/index.js:219:22)
    at ontouch (/Users/rmehra/esupport/code/asp_v4/node_modules/express-session/index.js:303:11)
    at /Users/rmehra/esupport/code/asp_v4/node_modules/connect-mongo/lib/connect-mongo.js:420:11
    at handleCallback (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/node_modules/mongodb/lib/collection.js:840:5
    at /Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:756:13
    at [object Object].Callbacks.emit (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
Stopping Express server
```

**Comment by Zertz** [comment]
> [When passing values as objects or arrays in URLs, they must be valid JSON](https://florianholzapfel.github.io/express-restify-mongoose/#querying)

`JSON.parse` is really strict, it would be amazing to have a better solution though! Basically something that can deal with quotes being there or not.

**Comment by ravishivt** [comment]
Understood, but couldn't we pre-process the query param in a try/catch to see if JSON.parse will result in a SyntaxError exception?  If it does, we could return a 400 instead of passing it to mongoose and having it generate an uncaught exception.

**Comment by Zertz** [comment]
Odd, [that's what it's supposed to do](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/middleware/prepareQuery.js#L107) actually...

**Comment by Zertz** [comment]
@ravishivt is this still an issue in 2.4/3.0 ?
