### ISSUE TITLE
Bad path in populate causes crash in 2.1.1

### ISSUE THREAD

**Issue by nategupt** [florianholzapfel/express-restify-mongoose#174]
Get the following crash on a bad element in populate. Ideally am trying to do a deep populate of "child" in post. (Original issue was reported under issue#137)

var postSchema = mongoose.Schema({
message: String,
user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
}
}

var userSchema = mongoose.Schema({
message: String,
child: { type: mongoose.Schema.Types.ObjectId, ref: 'Child' },
}
}

[GET] api.com/posts/?populate=useX  --->crashes (mis-spelt element)
[GET] api.com/posts/?populate=user.child --->crashes

/app/node_modules/express-restify-mongoose/lib/resource_filter.js:111
    if (path.caster && path.caster.options) {
            ^

TypeError: Cannot read property 'caster' of undefined
    at findExcludedFieldsFor (/app/node_modules/express-restify-mongoose/lib/resource_filter.js:111:13)
    at filterPopulated (/app/node_modules/express-restify-mongoose/lib/resource_filter.js:140:23)
    at filterObject (/app/node_modules/express-restify-mongoose/lib/resource_filter.js:163:7)
    at EventEmitter.<anonymous> (/app/node_modules/express-restify-mongoose/lib/operations.js:127:23)
    at EventEmitter.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Promise.safeEmit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
    at Promise.resolve (/app/node_modules/mongoose/lib/promise.js:113:23)
    at /app/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /app/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

**Comment by Zertz** [comment]
Thanks, that's very useful info!

Keep in mind that mongoose does not support deep populate so while the crash needs to be fixed, what you're trying to achieve cannot work.

**Comment by Zertz** [comment]
@nategupt Fixes for both bugs are in #175

**Comment by nategupt** [comment]
Thanks much! Verified the fix on my side as well.
