### ISSUE TITLE
GET/PUT an invalid object ID should return a 404, not 400

### ISSUE THREAD

**Issue by ravishivt** [florianholzapfel/express-restify-mongoose#184]
If I do a GET on /api/v1/files/1234, I get a 400 response and the following exception is generated:

```
Error
    at MongooseError.CastError (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/error/cast.js:18:16)
    at ObjectId.cast (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/schema/objectid.js:134:13)
    at ObjectId.castForQuery (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/schema/objectid.js:187:17)
    at module.exports (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/cast.js:205:32)
    at module.exports (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/cast.js:34:18)
    at Query.cast (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/query.js:2492:10)
    at Query.findOne (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/query.js:1237:10)
    at /Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/query.js:2114:21
    at new Promise.ES6 (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/promise.js:45:3)
    at Query.exec (/Users/rmehra/esupport/code/asp_v4/node_modules/mongoose/lib/query.js:2107:10)
    at /Users/rmehra/esupport/code/asp_v4/node_modules/express-restify-mongoose/lib/operations.js:101:101
    at Object.restify.serve.contextFilter (/Users/rmehra/esupport/code/asp_v4/lib/routes/api/files.ts:47:7)
    at getItem (/Users/rmehra/esupport/code/asp_v4/node_modules/express-restify-mongoose/lib/operations.js:100:13)
    at Layer.handle [as handle_request] (/Users/rmehra/esupport/code/asp_v4/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rmehra/esupport/code/asp_v4/node_modules/express/lib/router/route.js:131:13)
    at restify.serve.preMiddleware (/Users/rmehra/esupport/code/asp_v4/lib/routes/api/files.ts:30:5)
    at Layer.handle [as handle_request] (/Users/rmehra/esupport/code/asp_v4/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rmehra/esupport/code/asp_v4/node_modules/express/lib/router/route.js:131:13)
    at /Users/rmehra/esupport/code/asp_v4/node_modules/express-restify-mongoose/lib/middleware/prepareQuery.js:129:5
    at Layer.handle [as handle_request] (/Users/rmehra/esupport/code/asp_v4/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rmehra/esupport/code/asp_v4/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/rmehra/esupport/code/asp_v4/node_modules/express/lib/router/route.js:112:3)
```

Instead of this, could we check if the passed ID is a validly formatted Mongo ObjectID and immediately return a 404 if it is invalid?  Maybe using ```mongoose.Types.ObjectId.isValid(<passed ID>);``` or ```/^[0-9a-fA-F]{24}$/.test(<passed ID>)```.  I could set this up in preMiddleware but is there a better way of retrieving the padded ID than parsing it out of the req.baseUrl?

**Comment by ravishivt** [comment]
This is what I added to preMiddleware.  It works but isn't pretty.

```
if (req.method === "GET" || req.method === "PUT" || req.method === "DELETE") {
      var urlParts = req._parsedUrl.pathname.split('/');
      var objId = urlParts[urlParts.length - 1];
      if (objId !== apiName && !mongoose.Types.ObjectId.isValid(objId)) {
        return res.status(404).send("Not Found");
      }
    }
```

**Comment by Zertz** [comment]
**+1** However, the solution internally is a little more complicated because you can't simply assume `idProperty` is an `ObjectId`. We'd have to inspect `model.schema.path(idProperty)`

P.S. simplified version of your code:
```
if (req.params.id && !mongoose.Types.ObjectId.isValid(req.params.id)) {
  return res.sendStatus(404);
}
```

**Comment by ravishivt** [comment]
Thanks for the help.

**Comment by Zertz** [comment]
Actually, when `idProperty` is left default, we could check if it's valid since a MongoDB `_id` will always be an `ObjectId`.

**Comment by Zertz** [comment]
We could look for `CastError` in the `getItem`'s error handler and send 404 instead, which would indeed be more appropriate.
