### ISSUE TITLE
MongoDB 3.2 Limit / Skip not working

### ISSUE THREAD

**Issue by sascha1337** [florianholzapfel/express-restify-mongoose#215]
```
{ [MongoError: Failed to parse: { find: "users", filter: {}, skip: "0", limit: "30" }. 'skip' field must be numeric.]
  name: 'MongoError',
  message: 'Failed to parse: { find: "users", filter: {}, skip: "0", limit: "30" }. \'skip\' field must be numeric.',
  waitedMS: 0,
  ok: 0,
  errmsg: 'Failed to parse: { find: "users", filter: {}, skip: "0", limit: "30" }. \'skip\' field must be numeric.',
  code: 9,
  statusCode: 400 }
```

NPM Test Result:

  1) Express Read documents limit GET /Customers?limit=1 200:

      Uncaught AssertionError: 400 == 200
      + expected - actual

      -400
      +200
      
      at Request._callback (test/integration/read.js:172:18)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)

  2) Express Read documents skip GET /Customers?skip=1 200:

      Uncaught AssertionError: 400 == 200
      + expected - actual

      -400
      +200
      
      at Request._callback (test/integration/read.js:189:18)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)

  3) Express limit GET /Customers 200 - override limit in options (query.limit < options.limit):

      Uncaught AssertionError: 400 == 200
      + expected - actual

      -400
      +200
      
      at Request._callback (test/integration/options.js:173:16)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)

npm ERR! Test failed.  See above for more details.

**Comment by sascha1337** [comment]
i was about to check out other libraries, look what i found :dancer: 
https://github.com/wprl/baucis/issues/303

**Comment by Zertz** [comment]
Probably the parser is more strict than it was. I guess a simple `parseInt` might do the trick.

**Comment by sascha1337** [comment]
can you push a update today?

**Comment by Zertz** [comment]
I am currently setting up my new laptop, I'll try to work on a patch tonight or tomorrow.
