### ISSUE TITLE
Error: collection name must be a String

### ISSUE THREAD

**Issue by dejies** [florianholzapfel/express-restify-mongoose#336]
Hi,
i am using express-restify-mongoose to restify my mongoose model.
i am getting the following error : Error: collection name must be a String
please see the details below.

node version :4.2.5
app.js
=====

const express = require('express')
const bodyParser = require('body-parser')
const methodOverride = require('method-override')
const mongoose = require('mongoose')
mongoose.connect('mongodb://xxx.xxx.xxx.xxx:1111/theatre')

const restify = require('express-restify-mongoose')
const app = express()
const router = express.Router()
var Schema=mongoose.Schema;

app.use(bodyParser.json())
app.use(methodOverride())

var MovieSchema=new Schema({
	name:{
		type:String,
		required:true
	},
	storyline:String,
	country:String,
	language:String
	
	
});
 

restify.serve(router, mongoose.model('Movies', MovieSchema,{
  preRead: function (req, res, next) {
    console.log('i am before read')
    next()
  }
}
))

app.use(router)

app.listen(8080, () => {
  console.log('Express server listening on port 8080')
})

package.json
============
"dependencies": {
    "body-parser": "^1.17.1",
    "express": "^4.15.2",
    "express-restify-mongoose": "^4.1.3",
    "method-override": "^2.3.8",
    "mongoose": "^4.9.7"
  }

error
====
Error: collection name must be a String
    at Error (native)
    at checkCollectionName (D:\Personal\theatre\node_modules\mongoose\node_modules\mongodb\lib\utils.js:94:11)
    at new Collection (D:\Personal\theatre\node_modules\mongoose\node_modules\mongodb\lib\collection.js:63:3)
    at Db.collection (D:\Personal\theatre\node_modules\mongoose\node_modules\mongodb\lib\db.js:460:24)
    at NativeCollection.onOpen (D:\Personal\theatre\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:43:34)
    at open (D:\Personal\theatre\node_modules\mongoose\lib\connection.js:591:30)
    at NativeConnection.Connection.onOpen (D:\Personal\theatre\node_modules\mongoose\lib\connection.js:605:5)
    at D:\Personal\theatre\node_modules\mongoose\lib\connection.js:565:11
    at D:\Personal\theatre\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:71:5
    at D:\Personal\theatre\node_modules\mongoose\node_modules\mongodb\lib\db.js:237:5
    at connectHandler (D:\Personal\theatre\node_modules\mongoose\node_modules\mongodb\lib\server.js:339:7)
    at g (events.js:260:16)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at D:\Personal\theatre\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:299:14
    at D:\Personal\theatre\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:461:18
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

Thanks
Dejies

**Comment by Zertz** [comment]
There's a slight mistake in your code, the parenthesis should close after `MovieSchema` otherwide the third argument is being handled as if it was the collection's name.

```js
restify.serve(router, mongoose.model('Movies', MovieSchema), {
  preRead: function (req, res, next) {
    console.log('i am before read')
    next()
  }
})
```
